entradaDigitada = input('Digite algo: ')
print(entradaDigitada, ' é do tipo ', type(entradaDigitada))
print('Só tem espaços?', entradaDigitada.isspace())
print('É um número?', entradaDigitada.isnumeric())
print('É Alfanumérico?', entradaDigitada.isalnum())
print('É Alfabético?', entradaDigitada.isalpha())
print('Está maiúsculo?', entradaDigitada.isupper())
print('Está minúsculo?', entradaDigitada.islower())
print('Está capitalizado?', entradaDigitada.istitle())
